### ISSUE TITLE
[Add]: vpcresources.k8s.aws/v1beta1

### ISSUE THREAD

**Issue by tom10271** [metio/terraform-provider-k8s#115]
### Link to upstream specification(s)

https://github.com/aws/amazon-vpc-resource-controller-k8s

### SPDX license identifier for the upstream spec

Apache-2.0

### Name of the copyright holder

AWS

**Comment by sebhoss** [comment]
note to self: https://github.com/aws/amazon-vpc-resource-controller-k8s/tree/master/config/crd/bases is the direct link to the CRDs

**Comment by sebhoss** [comment]
The CRDs have been added in the latest release just now. I've added an example in https://registry.terraform.io/providers/metio/k8s/latest/docs/data-sources/vpcresources_k8s_aws_security_group_policy_v1beta1_manifest

Thanks for opening this ticket @tom10271 ❤️
